name: qyre_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Matter
      fonts:
        - asset: assets/fonts/Matter-Bold.otf
        - asset: assets/fonts/Matter-Light.otf
        - asset: assets/fonts/Matter-Medium.otf